// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvmgrlltatuqqvkxuldr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2bWdybGx0YXR1cXF2a3h1bGRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MjM0NTYsImV4cCI6MjA2ODk5OTQ1Nn0.-66keIYxyqZEU_n-7y5NOBssAKSOI877RooTO7T1te8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});